### ISSUE TITLE
Unable to run tasks (appcli 1.3.2+) due to missing docker binary

### ISSUE THREAD

**Issue by david-homley** [brightsparklabs/appcli#130]
Attempting to use the `task run` feature results in error:

> Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/local/lib/python3.8/site-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python3.8/site-packages/compose/cli/main.py", line 863, in run
    run_one_off_container(
  File "/usr/local/lib/python3.8/site-packages/compose/cli/main.py", line 1347, in run_one_off_container
    exit_code = call_docker(
  File "/usr/local/lib/python3.8/site-packages/compose/cli/main.py", line 1442, in call_docker
    raise UserError(errors.docker_not_found_msg("Couldn't find `docker` binary."))
  File "/usr/local/lib/python3.8/site-packages/compose/cli/errors.py", line 137, in docker_not_found_msg
    problem, docker_install_url())
  File "/usr/local/lib/python3.8/site-packages/compose/cli/errors.py", line 143, in docker_install_url
    elif is_ubuntu():
  File "/usr/local/lib/python3.8/site-packages/compose/cli/utils.py", line 76, in is_ubuntu
    return platform.system() == 'Linux' and platform.linux_distribution()[0] == 'Ubuntu'
AttributeError: module 'platform' has no attribute 'linux_distribution'
2021-04-30T01:41:31+0000 INFO: Task service finished with code [1]

**Comment by thomas-anderson-bsl** [comment]
It looks like `docker-compose run` calls the `docker` binary directly, in contrast with `docker-compose up` which just needs the docker.sock.

We removed the `docker` installation in the `appcli` container in a commit which first appeared in tag `1.3.2`.

https://github.com/brightsparklabs/appcli/commit/92349d5e1de1a10e97e25a12bb3ee104efb44bd6#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

This was done to drastically reduce the size of the appcli docker image.

What this means is that `task run` will not work for appcli versions `1.3.2` and `1.3.3` unless docker is installed on top of the appcli image.

The fix we're investigating now is to embed the static binary of `docker` into the image. This will fix `task run`, as well as #115 
https://docs.docker.com/engine/install/binaries/#install-static-binaries

**Comment by thomas-anderson-bsl** [comment]
Resolved by #136
